version: '2'

services:
   beego:
     build: ./beego
     ports:
       - '80:80'
       - '443:443'
     restart: always
     volumes:
       - /root/nav/:/go/src/v2nav
       - /root/nav/letsencrypt_data:/etc/letsencrypt
